# Generated by Django 4.2.5 on 2023-09-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedCamping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=120)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DetoxCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=120)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DrugTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=120)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Foodbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=120)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=120)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=120)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SafeConsumptionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=120)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shelters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=120)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
                ('charts_allowed', models.BooleanField(default=False)),
                ('meals', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('category', models.BooleanField(default=False)),
            ],
        ),
    ]
